server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://invoice_ops_backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header Sf-Context-Current-User $http_sf_context_current_user;
        proxy_set_header Sf-Context-Current-User-Email $http_sf_context_current_user_email;
    }

    location / {
        proxy_pass http://invoice_ops_frontend:80/;
        proxy_set_header Host $host;
    }
}
